In [1]:
import csv
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt
from datetime import datetime
from sklearn.model_selection import train_test_split

In [2]:
import tensorflow as tf
print("Num GPUs Available: ", len(tf.config.list_physical_devices('GPU')))

2022-12-05 00:24:24.216750: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX_VNNI FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-12-05 00:24:24.361877: I tensorflow/core/util/port.cc:104] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2022-12-05 00:24:24.858371: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory
2022-12-05 00:24:24.858518: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not l

Num GPUs Available:  0


2022-12-05 00:24:25.385727: E tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:267] failed call to cuInit: CUDA_ERROR_SYSTEM_DRIVER_MISMATCH: system has unsupported display driver / cuda driver combination
2022-12-05 00:24:25.385754: I tensorflow/compiler/xla/stream_executor/cuda/cuda_diagnostics.cc:169] retrieving CUDA diagnostic information for host: danilo-Nitro-AN515-58
2022-12-05 00:24:25.385758: I tensorflow/compiler/xla/stream_executor/cuda/cuda_diagnostics.cc:176] hostname: danilo-Nitro-AN515-58
2022-12-05 00:24:25.385892: I tensorflow/compiler/xla/stream_executor/cuda/cuda_diagnostics.cc:200] libcuda reported version is: 510.108.3
2022-12-05 00:24:25.385904: I tensorflow/compiler/xla/stream_executor/cuda/cuda_diagnostics.cc:204] kernel reported version is: 525.60.11
2022-12-05 00:24:25.385907: E tensorflow/compiler/xla/stream_executor/cuda/cuda_diagnostics.cc:313] kernel version 525.60.11 does not match DSO version 510.108.3 -- cannot find working devices in this co

In [3]:
train_data = pd.read_csv("data/train.csv")

In [4]:
# new features
train_data["url_count"] = train_data["urls"].apply(lambda s: s[1:-1].count("\'")/2)
train_data["text_len"] = train_data["text"].apply(lambda s: len(s))
train_data["hashtags_count"] = train_data["hashtags"].apply(lambda s: s[1:-1].count("\'")/2)
train_data["day"] = train_data["timestamp"].apply(lambda t: datetime.utcfromtimestamp(t/1000).day)
train_data["hour"] = train_data["timestamp"].apply(lambda t: datetime.utcfromtimestamp(t/1000).hour)

# indicators of keywords
train_data["Macron"] =  train_data["text"].apply(lambda s: ("macron" in s.lower().split()))
train_data["Zemmour"] =  train_data["text"].apply(lambda s: ("zemmour" in s.lower().split()))
train_data["Melenchon"] =  train_data["text"].apply(lambda s: ("melenchon" in s.replace("é","e").lower().split()))
train_data["rt"] =  train_data["text"].apply(lambda s: ("rt" in s.lower().split()))

In [5]:
# separate target
target = train_data["retweets_count"]
train_data = train_data.drop(["retweets_count"], axis=1)

In [6]:
# select useful columns
train_data_filtered = train_data.drop(["text", "urls", "mentions", "hashtags", "timestamp", "TweetID"], axis=1)

# Standardize the data
normal_columns = train_data_filtered.drop(["hour", "verified", "Macron", "Zemmour", "Melenchon", "url_count", "rt"], axis=1).columns
mu, sigma = train_data_filtered[normal_columns].mean(axis=0), train_data_filtered[normal_columns].std(axis=0)
train_data_filtered.loc[:, normal_columns] = (train_data_filtered[normal_columns] - mu) / sigma

In [7]:
display(train_data_filtered)

favorites_count  followers_count  statuses_count  friends_count  \
0             -0.054757        -0.063622        3.575856       0.866468   
1             -0.054757        -0.077459       -0.415125      -0.469565   
2             -0.053583        -0.070310       -0.175076       0.214033   
3             -0.054757        -0.077786       -0.414631      -0.583032   
4             -0.054757        -0.024083       -0.200855       3.748287   
...                 ...              ...             ...            ...   
353964        -0.054757        -0.077659       -0.410777      -0.561057   
353965        -0.054757        -0.077448       -0.325607      -0.532291   
353966        -0.054757        -0.070525       -0.417806       0.649922   
353967        -0.054757        -0.077255       -0.419799      -0.455182   
353968        -0.054757        -0.077790       -0.423362      -0.573443   

        verified  url_count  text_len  hashtags_count       day  hour  Macron  \
0              0        0.0 -0.865385       -0.384248 -1.030050     5    True   
1              0        0.0 -1.466000       -0.384248  1.385496    12   False   
2              0        0.0 -1.225754       -0.384248  0.177723    18   False   
3              0        1.0  1.272804       -0.384248 -0.124220    11   False   
4              0        0.0 -1.057582       -0.384248 -0.124220    11    True   
...          ...        ...       ...             ...       ...   ...     ...   
353964         0        1.0 -0.961483       -0.384248  0.479666    13   False   
353965         0        0.0 -0.024524       -0.384248 -0.728107     8   False   
353966         0        0.0 -0.985508       -0.384248  1.083553    12   False   
353967         0        0.0 -1.105631       -0.384248 -1.030050     8   False   
353968         0        0.0 -0.601114       -0.384248  1.083553    11    True   

        Zemmour  Melenchon     rt  
0         False      False   True  
1         False      False  False  
2         False      False  False  
3         False      False  False  
4         False      False  False  
...         ...        ...    ...  
353964    False      False  False  
353965    False      False  False  
353966     True      False  False  
353967    False      False  False  
353968    False      False  False  

[353969 rows x 14 columns]

In [8]:
emb_matrix = np.load("data/train_emb_matrix.npy")
print(train_data_filtered.shape, emb_matrix.shape)

(353969, 14) (353969, 20, 16)


In [9]:
data_newdim = np.expand_dims(np.array(train_data_filtered), axis=1)
data_reshaped = np.broadcast_to(data_newdim, (emb_matrix.shape[0], emb_matrix.shape[1], train_data_filtered.shape[1]))
data_reshaped[0][:2]

array([[-0.05475705537294453, -0.06362175216471, 3.575856294985138,
        0.8664677648458644, 0, 0.0, -0.865384899170238,
        -0.3842477354707097, -1.0300503271633217, 5, True, False, False,
        True],
       [-0.05475705537294453, -0.06362175216471, 3.575856294985138,
        0.8664677648458644, 0, 0.0, -0.865384899170238,
        -0.3842477354707097, -1.0300503271633217, 5, True, False, False,
        True]], dtype=object)

In [10]:
# full_matrix = data_reshaped

In [11]:
full_matrix = np.concatenate((data_reshaped, emb_matrix), axis=2)

In [12]:
print(full_matrix[0][:2])

[[-0.05475705537294453 -0.06362175216471 3.575856294985138
  0.8664677648458644 0 0.0 -0.865384899170238 -0.3842477354707097
  -1.0300503271633217 5 True False False True 0.5982136726379395
  -0.41382595896720886 -1.5026640892028809 0.43765056133270264
  -0.627597987651825 -0.24090319871902466 0.987481415271759
  0.31742244958877563 -0.33321428298950195 -0.2305217683315277
  0.5702282190322876 -0.009200990200042725 0.6182277798652649
  -0.049457207322120667 0.052918002009391785 1.7371989488601685]
 [-0.05475705537294453 -0.06362175216471 3.575856294985138
  0.8664677648458644 0 0.0 -0.865384899170238 -0.3842477354707097
  -1.0300503271633217 5 True False False True 0.31452399492263794
  1.6592214107513428 0.035753414034843445 -0.6295616626739502
  -0.6962608695030212 0.2110033929347992 0.459422767162323
  0.21427248418331146 0.6258943676948547 0.6146286725997925
  -0.5703885555267334 -0.2553447484970093 0.19011209905147552
  0.08015090972185135 -0.7017520666122437 -0.25351837277412415]

In [13]:
# full_matrix = np.expand_dims(full_matrix, axis=(2, 1))
full_matrix = full_matrix[..., np.newaxis]

In [14]:
print(full_matrix.shape)

(353969, 20, 30, 1)


In [15]:
print(full_matrix[0][:2])

[[[-0.05475705537294453]
  [-0.06362175216471]
  [3.575856294985138]
  [0.8664677648458644]
  [0]
  [0.0]
  [-0.865384899170238]
  [-0.3842477354707097]
  [-1.0300503271633217]
  [5]
  [True]
  [False]
  [False]
  [True]
  [0.5982136726379395]
  [-0.41382595896720886]
  [-1.5026640892028809]
  [0.43765056133270264]
  [-0.627597987651825]
  [-0.24090319871902466]
  [0.987481415271759]
  [0.31742244958877563]
  [-0.33321428298950195]
  [-0.2305217683315277]
  [0.5702282190322876]
  [-0.009200990200042725]
  [0.6182277798652649]
  [-0.049457207322120667]
  [0.052918002009391785]
  [1.7371989488601685]]

 [[-0.05475705537294453]
  [-0.06362175216471]
  [3.575856294985138]
  [0.8664677648458644]
  [0]
  [0.0]
  [-0.865384899170238]
  [-0.3842477354707097]
  [-1.0300503271633217]
  [5]
  [True]
  [False]
  [False]
  [True]
  [0.31452399492263794]
  [1.6592214107513428]
  [0.035753414034843445]
  [-0.6295616626739502]
  [-0.6962608695030212]
  [0.2110033929347992]
  [0.459422767162323]
  [0.2

In [16]:
X_train, X_eval, y_train, y_eval = train_test_split(full_matrix, target.values, random_state=42, test_size=0.1)

: 

: 

In [ ]:
print(X_train.shape, y_train.shape, X_eval.shape, y_eval.shape)

: 

: 

In [ ]:
# filter = 200000

# X_train = X_train[filter:]
# y_train = y_train[filter:]

: 

: 

In [ ]:
print(X_train.shape, y_train.shape, X_eval.shape, y_eval.shape)

: 

: 

In [ ]:
import tensorflow as tf

: 

: 

In [ ]:
from keras.models import Sequential
from keras.layers import Conv2D
from keras.layers import MaxPooling2D
from keras.layers import Dense
from keras.layers import Flatten
from keras.layers import Dropout

n_timesteps = X_train.shape[1]
input_features = X_train.shape[2]

: 

: 

In [ ]:
model = Sequential()
model.add(Conv2D(8, (3, 3), activation='relu', padding='same',
                            input_shape=(X_train.shape[1], X_train.shape[2], 1)))
model.add(Conv2D(8, (3, 3), activation='relu', padding='same',
                            input_shape=(X_train.shape[1], X_train.shape[2], 1)))
model.add(MaxPooling2D((2, 2)))
model.add(Flatten())
model.add(Dense(32, activation='relu'))
model.add(Dropout(0.2))
model.add(Dense(32, activation='relu'))
model.add(Dropout(0.2))
model.add(Dense(32, activation='relu'))
model.add(Dropout(0.2))
model.add(Dense(1, activation='linear'))

: 

: 

In [ ]:
# model = Sequential()
# model.add(Conv2D(32, (3, 3), activation='relu', kernel_initializer='he_uniform', padding='same', input_shape=(32, 32, 3)))
# model.add(Conv2D(32, (3, 3), activation='relu', kernel_initializer='he_uniform', padding='same'))
# model.add(MaxPooling2D((2, 2)))
# model.add(Conv2D(64, (3, 3), activation='relu', kernel_initializer='he_uniform', padding='same'))
# model.add(Conv2D(64, (3, 3), activation='relu', kernel_initializer='he_uniform', padding='same'))
# model.add(MaxPooling2D((2, 2)))
# model.add(Conv2D(128, (3, 3), activation='relu', kernel_initializer='he_uniform', padding='same'))
# model.add(Conv2D(128, (3, 3), activation='relu', kernel_initializer='he_uniform', padding='same'))
# model.add(MaxPooling2D((2, 2)))
# model.add(Flatten())
# model.add(Dense(128, activation='relu', kernel_initializer='he_uniform'))
# model.add(Dense(10, activation='softmax'))

: 

: 

In [ ]:
# model = tf.keras.models.Sequential([
#   tf.keras.layers.Dense(64, activation='relu'),
#   tf.keras.layers.Dense(1),
# ])

: 

: 

In [ ]:
# import tensorflow_addons as tfa
# optimizer = tfa.optimizers.AdamW(learning_rate=1e-3, weight_decay=1e-4)
# model.compile(optimizer=optimizer, loss='mae')

: 

: 

In [ ]:
model.compile(optimizer="adam", loss='mae')

: 

: 

In [ ]:
model.summary()

: 

: 

In [ ]:
history = model.fit(X_train.astype(np.float32), y_train.astype(np.float32), epochs=180, batch_size=256,
         validation_data=(X_eval.astype(np.float32), y_eval.astype(np.float32)), shuffle=True)

: 

: 

In [ ]:
plt.plot(history.epoch, history.history["loss"], 'b', label='Training loss')
plt.plot(history.epoch, history.history["val_loss"], 'g', label='Validation loss')
plt.title('Training loss')
plt.xlabel('Epochs')
plt.ylabel('Loss')
plt.legend()
plt.show()

: 

: 

In [ ]:
model.evaluate(X_eval.astype(np.float32),  y_eval.astype(np.float32), verbose=2)

: 

: 

In [ ]:
pred = model.predict(X_train.astype(np.float32))
print(pred)

: 

: 

In [ ]:
# plt.scatter(X_train["favorites_count"], model.predict(X_train))
# plt.scatter(X_train["favorites_count"], y_train.values.astype(np.float32))

: 

: 

In [ ]:
# evaluation

eval_data = pd.read_csv("data/evaluation.csv")
tweets = eval_data["TweetID"]

: 

: 

In [ ]:
eval_data["url_count"] = eval_data["urls"].apply(lambda s: s[1:-1].count("\'")/2)
eval_data["text_len"] = eval_data["text"].apply(lambda s: len(s))
eval_data["hashtags_count"] = eval_data["hashtags"].apply(lambda s: s[1:-1].count("\'")/2)
eval_data["day"] = eval_data["timestamp"].apply(lambda t: datetime.utcfromtimestamp(t/1000).day)
eval_data["hour"] = eval_data["timestamp"].apply(lambda t: datetime.utcfromtimestamp(t/1000).hour)
eval_data["Macron"] =  eval_data["text"].apply(lambda s: ("macron" in s.lower().split()))
eval_data["Zemmour"] =  eval_data["text"].apply(lambda s: ("zemmour" in s.lower().split()))
eval_data["Melenchon"] =  eval_data["text"].apply(lambda s: ("melenchon" in s.lower().split()))
eval_data["rt"] =  eval_data["text"].apply(lambda s: ("rt" in s.lower().split()))

# print("sentiment analysis...")
# eval_data["compound"] =  eval_data["text"].apply(lambda s: sia.polarity_scores(s)['compound'])

eval_data = eval_data.drop(["text", "urls", "mentions", "hashtags", "timestamp", "TweetID"], axis=1)

# normalize
eval_data.loc[:, normal_columns] = (eval_data.loc[:, normal_columns] - mu) / sigma

print(eval_data)

pred = model.predict(eval_data.values.astype(np.float32))

print(pred)

# output normalization
for i,p in enumerate(pred):
    if p<0: pred[i] = 0

: 

: 

In [ ]:
with open("data/predictions.csv", 'w') as f:
    writer = csv.writer(f)
    writer.writerow(["TweetID", "retweets_count"])
    for index, prediction in enumerate(pred):
        writer.writerow([str(tweets[index]) , str(int(prediction))])

: 

: 